### ISSUE TITLE
Make a few examples

### ISSUE THREAD

**Issue by fretchen** [synqs/pennylane-ls#3]
Hong-Ou-Mandel with Bosons a la Cindy Regal
Hong-Ou-Mandel with Fermions a la Selim Jochim

Complex states on a collective spin a la Markus Oberthaler
Dynamical gauge fields a la Freddi Fred

**Comment by fretchen** [comment]
Add them to the repo

**Comment by TheNewYorkerFlute** [comment]
Not done yet
