### ISSUE TITLE
Interaction must apply to all wires

### ISSUE THREAD

**Issue by fretchen** [synqs/pennylane-ls#34]
Why do we have to set the wires then ?

**Comment by TheNewYorkerFlute** [comment]
@fretchen You mean this problem 

![image](https://user-images.githubusercontent.com/39969008/130761565-ffefd3b8-00a8-4862-b98f-f2ae1a6676f5.png)

right?

**Comment by TheNewYorkerFlute** [comment]
Okay, this one is fixed 

![image](https://user-images.githubusercontent.com/39969008/130765918-fc4ab308-a295-4ae5-8081-53769e720ad8.png)

**Comment by TheNewYorkerFlute** [comment]
@fretchen Is this better for you? Now you can choose :)

**Comment by TheNewYorkerFlute** [comment]
@fretchen Sorry I misunderstood your point. The operator class of pennylane demands to specify the wires the operator acts on. So I would not call this a bug. It's specific to pennylane.
