### ISSUE TITLE
enforce pylint and proper documentation

### ISSUE THREAD

**Issue by fretchen** [synqs/pennylane-ls#49]
We have to make sure that the code is nicely running. 

I have a number of questions @cvjjm 

- do you use something like `tox` or things like this for automatic runs including tests, documentation and pylint ?
- And do you know if there is some standard `.pylintrc`for pennylane packages ?

**Comment by cvjjm** [comment]
We are not (yet) using tox.

There is the .pylintrc of main PL [here](https://github.com/PennyLaneAI/pennylane/blob/master/.pylintrc).
