### ISSUE TITLE
proper gate naming for qudit gates and fermion gates

### ISSUE THREAD

**Issue by fretchen** [synqs/pennylane-ls#50]
We spent quite some time to get this consistent within https://github.com/Qiskit-Extensions/qiskit-cold-atom and it would be good to have something that works properly here.

# For the spins 

- We have in `qiskit-cold-atom` the gate classes like `RLXGate`, they can be appended to the circuit as `circuit.rlx` and communicate to the server the string `rlx`. 
- In our case we have defined `rLx` as a class and this just completely inconsistent. @cvjjm what is the pennylane approach of such namings ?

# For the fermions

- We have a similiar discussion. The gates strings for the back-ends are now `fhop`, `fint` and `fphase`. I think that they make quite some sense, but here again we should make sure to be consistent with other packages and the pennylane approach if we adapt them within the package. @cvjjm any opinions here ?

**Comment by cvjjm** [comment]
In PennyLane gates are subclasses of the `Operation` class and thus (as all classes in python) start with an upper case letter and use "CamelCase".

I think that all fermionic operations that have a natural qubit cousin for which PL [already has a gate](https://pennylane.readthedocs.io/en/stable/introduction/operations.html) should use the same name.  This is what we did with `PauliZ`, which is (\hat n-1)/2 in the fermionic (and bosonic) case.

All genuinely new gates should get a "descriptive" name. There is no need to make them short as they will usually be the only thin on the respective line of code.

Following this logic I would not put an "f" in front of the fermionic operations. Hopping of Fermions and Bosons could/should be done with the same operation, it will just have a different meaning depending on the device the circuit is executed on. We actually decided to use "Tunneling" and I like it better as it conveys more that this is a continuous gate. Maybe "Hop" can be the discrete gate that kicks a particle from one orbital entirely to the other?

I think from a user perspective things like `FInt`, or `RLX ` are not great.  Without reading the documentation they provide zero insight into what is happening or how these gates relate to "known" gates.

Does `RLX` not essentially reduce to `RX` in the qubit case? If so, I would just call it RX. Similarly, isn't your `RLZLZGate` what is called `IsingZZ` in PennyLane?
